baseURL       = "http://dobiecoin.com/"
languageCode  = "en-us"
title         = "Dobiecoin | Anti-counterfeit Watchdog"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "#"
    weight  = 1
  [[menu.nav]]
    name    = "Merchandise"
    url     = "#"
    weight  = 2
  [[menu.nav]]
    name    = "White Paper"
    url     = "#"
    weight  = 3
  [[menu.nav]]
    name    = "Dobiecoin Contract"
    url     = "#"
    weight  = 4
  [[menu.nav]]
    name    = "Pups for adoption"
    url     = "#"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Dobiecoin - Anti-counterfeit Watchdog"
  author = "DobieTeam"
  # Google Analitycs
  googleAnalitycsID = "G-BBFTB0H4GQ"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re raising the first Digital Watchdog"
    tagline               = "Anti-counterfeit Watchdog"
    primary_button        = "Dobiecoin Pups"
    primary_button_url    = "#"
    secondary_button      = "Telegram Group"
    secondary_button_url  = "https://t.me/dobiecoin"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "DOBIECOIN PUPS"
    primary_button      = "Pups for Adoption"
    primary_button_url  = "#"
    secondary_button    = "Telegram Group"
    secondary_button_url = "https://t.me/dobiecoin"

  [params.fund]
    enable              = true
    background_image    = "images/backgrounds/cta-2.jpg"
    title               = "HELP RAISING A DOGIECOIN PUP"
    subtitle            = "''We make a living by what we get, but we make a life by what we give''"
    primary_button      = "Fundraiser"
    primary_button_url  = "#"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Dobiecoin"
      address = "Anti-counterfeit Watchdog"
      phone   = "woof"
      email   = "woof"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Merchandise"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "White Paper"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Dobiecoin Contract"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Pups for Adoption"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/dobiecoin"
        [[params.footer.social.link]]
          name = "Telegram"
          url  = "https://t.me/dobiecoin"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "To beat counterfeits by raising the first Digital Watchdog to protect originality and authenticity."